"""A compact, useful documentation site with precisely scoped comparison defects."""

from __future__ import annotations

from html import escape

from .base import Planted, Request, Response


_T = {
    "en": {"brand":"Northstar Docs","home":"Overview","guide":"Guide","api":"API","faq":"FAQ","eyebrow":"Reference library","headline":"Make the next release predictable.","lead":"Northstar gives small teams a clear, observable path from idea to production.","help":"Need a hand? Start with the guide or ask your workspace owner.","guide_title":"A practical guide","guide_lead":"Set up your first project, then establish the boundaries that keep it healthy.","limits":"Limits and safeguards","limits_text":"Rate limits protect the shared service and make capacity easy to reason about.","api_title":"API reference","api_text":"Every request uses JSON and a versioned endpoint.","faq_title":"Frequently asked questions","faq_text":"Answers for the questions teams ask while shipping.","related":"Related questions","related_text":"How do I rotate a token? · Where can I see usage?","read":"Read guide","search":"Search the documentation","sections":"Browse by task","popular":"Popular pages","footer":"Northstar Docs · Built for teams that ship carefully.","start":"Start a project","deploy":"Prepare a deployment","observe":"Monitor a release","auth":"Manage access","start_text":"Create a project, invite teammates, and make the first environment.","deploy_text":"Connect checks, release a change, and understand its status.","observe_text":"Read events, usage, and the signals that need attention.","auth_text":"Issue scoped tokens and review access without slowing the team.","quickstart":"Quickstart","webhooks":"Webhooks","tokens":"Personal access tokens","usage":"Usage & limits","faq1":"How do I create a project?","faq1a":"Create it from the workspace, then copy its project ID into your first request.","faq2":"Can I use a token in CI?","faq2a":"Yes. Create a scoped service token and store it in your CI secret manager.","faq3":"Where do I see failed deliveries?","faq3a":"Open the event stream for a project and filter by delivery status."},
    "ar": {"brand":"توثيق نورث ستار","home":"نظرة عامة","guide":"الدليل","api":"واجهة البرمجة","faq":"الأسئلة الشائعة","eyebrow":"مكتبة مرجعية","headline":"اجعل الإصدار القادم متوقعًا.","lead":"يمنح نورث ستار الفرق الصغيرة مسارًا واضحًا ومرئيًا من الفكرة إلى الإنتاج.","help":"هل تحتاج إلى مساعدة؟ ابدأ بالدليل أو اسأل مسؤول مساحة العمل.","guide_title":"دليل عملي","guide_lead":"أعد مشروعك الأول ثم ضع الحدود التي تحافظ على صحته.","limits":"الحدود ووسائل الحماية","limits_text":"تحمي حدود المعدل الخدمة المشتركة وتجعل السعة سهلة الفهم.","api_title":"مرجع واجهة البرمجة","api_text":"يستخدم كل طلب JSON ونقطة نهاية ذات إصدار.","faq_title":"الأسئلة الشائعة","faq_text":"إجابات عن الأسئلة التي تطرحها الفرق أثناء الإطلاق.","related":"أسئلة ذات صلة","related_text":"كيف أبدّل رمزًا؟ · أين أرى الاستخدام؟","read":"اقرأ الدليل","search":"ابحث في التوثيق","sections":"تصفح حسب المهمة","popular":"صفحات شائعة","footer":"توثيق نورث ستار · للفرق التي تطلق بعناية.","start":"ابدأ مشروعًا","deploy":"جهّز إطلاقًا","observe":"راقب إصدارًا","auth":"أدر الوصول","start_text":"أنشئ مشروعًا وادعُ زملاءك وجهّز البيئة الأولى.","deploy_text":"اربط الفحوصات وأطلق تغييرًا وافهم حالته.","observe_text":"اقرأ الأحداث والاستخدام والإشارات التي تحتاج اهتمامًا.","auth_text":"أنشئ رموزًا محددة النطاق وراجع الوصول دون إبطاء الفريق.","quickstart":"البدء السريع","webhooks":"خطافات الويب","tokens":"رموز الوصول الشخصية","usage":"الاستخدام والحدود","faq1":"كيف أنشئ مشروعًا؟","faq1a":"أنشئه من مساحة العمل ثم انسخ معرّف المشروع في طلبك الأول.","faq2":"هل يمكنني استخدام رمز في التكامل المستمر؟","faq2a":"نعم. أنشئ رمز خدمة محدد النطاق واحفظه في مدير أسرار التكامل.","faq3":"أين أرى عمليات التسليم الفاشلة؟","faq3a":"افتح تدفق الأحداث للمشروع وصفّه حسب حالة التسليم."},
}


class DocsSite:
    name = "docs"
    title = "Northstar Docs"
    planted = [
        Planted("untranslated", "locale", "/guide", "Arabic renders one guide heading as its translation key."),
        Planted("low_contrast", "theme", "/", "Dark-only secondary help text uses #6b6b6b."),
        Planted("divergence", "viewport", "/faq", "Related questions disappear under 768px."),
    ]

    def handle(self, request: Request) -> Response:
        path = request.path.rstrip("/") or "/"
        if path not in {"/", "/guide", "/api", "/faq"}:
            return Response.not_found()
        return Response.html(self._page(_T[request.lang], request.lang, request.theme, path, request.mount))

    def _page(self, t: dict[str, str], lang: str, theme: str, path: str, mount: str) -> str:
        direction = "rtl" if lang == "ar" else "ltr"
        nav = "".join(f'<a href="{mount}{href}">{escape(t[key])}</a>' for href, key in (("/", "home"), ("/guide", "guide"), ("/api", "api"), ("/faq", "faq")))
        pages = {"/": self._home(t, mount), "/guide": self._guide(t, lang), "/api": self._api(t), "/faq": self._faq(t)}
        return f'''<!doctype html><html lang="{lang}" dir="{direction}" data-theme="{theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{escape(t["brand"])}</title><style>
*{{box-sizing:border-box}}:root{{--bg:#fbfaf6;--panel:#fff;--ink:#1f282a;--muted:#4c5a5b;--line:#d7ddda;--signal:#126b63;--help:#52605e}}[data-theme="dark"]{{--bg:#131b1d;--panel:#1c282a;--ink:#f1eee5;--muted:#c4ceca;--line:#3c4a4c;--signal:#8fd6c9;--help:#6b6b6b}}body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 Georgia,serif}}a{{color:inherit}}.wrap{{max-width:1100px;margin-inline:auto;padding-inline:28px}}header{{border-block-end:1px solid var(--line)}}.top{{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:28px}}.brand{{font:700 20px/1 Georgia,serif;text-decoration:none;letter-spacing:.03em}}nav{{display:flex;flex-wrap:wrap;gap:17px;font:700 13px/1 system-ui,sans-serif}}nav a{{text-decoration:none}}nav a:hover,a:focus-visible{{color:var(--signal)}}main{{padding-block:54px}}.kicker{{color:var(--signal);font:700 12px/1 system-ui,sans-serif;letter-spacing:.14em;text-transform:uppercase}}h1,h2,h3{{line-height:1.12}}h1{{font-size:clamp(2.5rem,6vw,4.8rem);letter-spacing:-.035em;margin:13px 0 22px;max-inline-size:15ch}}h2{{font-size:1.65rem;margin:0 0 8px}}h3{{font-size:1.08rem;margin:0}}.lead{{font-size:1.15rem;max-width:620px;color:var(--muted)}}.help-text{{margin-block:28px;color:var(--help);border-inline-start:3px solid var(--line);padding-inline-start:16px}}.cta{{display:inline-flex;min-block-size:44px;align-items:center;margin-block-start:12px;background:var(--signal);color:#fff;padding-inline:17px;text-decoration:none;font:700 14px/1 system-ui,sans-serif}}[data-theme="dark"] .cta{{color:#07231f}}.search{{display:flex;align-items:center;max-width:680px;margin-block:32px 42px;background:var(--panel);border:1px solid var(--line);padding-inline:16px}}.search input{{inline-size:100%;min-block-size:52px;border:0;background:transparent;color:var(--ink);font:inherit;outline:0}}.section-grid,.two-col{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-block:24px 44px}}.doc-card,.popular,pre,.related-questions,details{{background:var(--panel);border:1px solid var(--line)}}.doc-card{{padding:22px;text-decoration:none;min-block-size:150px}}.doc-card p,.popular li{{color:var(--muted)}}.popular{{padding:22px 28px}}.popular ol{{margin:0;padding-inline-start:22px}}.popular li{{padding-block:8px}}pre{{padding:20px;overflow:auto;color:var(--ink)}}code{{font:14px/1.55 ui-monospace,SFMono-Regular,monospace}}details{{padding:17px 20px;margin-block:10px}}summary{{cursor:pointer;font-weight:bold}}details p{{color:var(--muted)}}.related-questions{{margin-block-start:44px;padding:22px}}footer{{border-block-start:1px solid var(--line);color:var(--muted);font-size:.9rem;padding-block:28px}}@media (max-width:767px){{.related-questions{{display:none}}.wrap{{padding-inline:18px}}main{{padding-block:40px}}.top{{align-items:flex-start;padding-block:18px}}.section-grid,.two-col{{grid-template-columns:1fr}}}}
</style></head><body><header><div class="wrap top"><a class="brand" href="{mount}/">{escape(t["brand"])}</a><nav aria-label="Primary">{nav}</nav></div></header><main class="wrap">{pages[path]}</main><footer><div class="wrap">{escape(t["footer"])}</div></footer></body></html>'''

    def _home(self, t: dict[str, str], mount: str) -> str:
        cards = "".join(f'<a class="doc-card" href="{mount}/guide"><h3>{escape(t[key])}</h3><p>{escape(t[key + "_text"])}</p></a>' for key in ("start", "deploy", "observe", "auth"))
        popular = "".join(f'<li><a href="{mount}/guide">{escape(t[key])}</a></li>' for key in ("quickstart", "webhooks", "tokens", "usage"))
        return f'<p class="kicker">{escape(t["eyebrow"])}</p><h1>{escape(t["headline"])}</h1><p class="lead">{escape(t["lead"])}</p><label class="search"><span aria-hidden="true">⌕</span><input type="search" name="q" autocomplete="off" placeholder="{escape(t["search"])}" aria-label="{escape(t["search"])}"></label><a class="cta" href="{mount}/guide">{escape(t["read"])} →</a><p class="help-text">{escape(t["help"])}</p><h2>{escape(t["sections"])}</h2><section class="section-grid">{cards}</section><section class="popular"><h2>{escape(t["popular"])}</h2><ol>{popular}</ol></section>'

    def _guide(self, t: dict[str, str], lang: str) -> str:
        limits_heading = "guide.sections.limits.title" if lang == "ar" else t["limits"]
        return f'<p class="kicker">{escape(t["guide"])}</p><h1>{escape(t["guide_title"])}</h1><p class="lead">{escape(t["guide_lead"])}</p><section class="two-col"><div><h2>{escape(limits_heading)}</h2><p>{escape(t["limits_text"])}</p></div><pre><code>northstar init --project atlas\nnorthstar env add production</code></pre></section><h2>{escape(t["quickstart"])}</h2><pre><code>POST /v1/projects\n{{"name": "atlas", "region": "eu-west"}}</code></pre>'

    def _api(self, t: dict[str, str]) -> str:
        return f'<p class="kicker">{escape(t["api"])}</p><h1>{escape(t["api_title"])}</h1><p class="lead">{escape(t["api_text"])}</p><section class="two-col"><pre><code>GET /v1/projects\nAuthorization: Bearer ns_live_…</code></pre><div><h2>200 OK</h2><p>{escape(t["observe_text"])}</p></div></section><h2>{escape(t["webhooks"])}</h2><pre><code>{{"event":"deployment.ready",\n "project":"atlas"}}</code></pre>'

    def _faq(self, t: dict[str, str]) -> str:
        questions = "".join(f'<details><summary>{escape(t[key])}</summary><p>{escape(t[key + "a"])}</p></details>' for key in ("faq1", "faq2", "faq3"))
        return f'<p class="kicker">{escape(t["faq"])}</p><h1>{escape(t["faq_title"])}</h1><p class="lead">{escape(t["faq_text"])}</p><section class="faq-list">{questions}</section><section class="related-questions"><h2>{escape(t["related"])}</h2><p>{escape(t["related_text"])}</p></section>'
